spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3396/springtutorial
    username: "root"
    password: "marper96"
  jpa:
    hibernate:ddl-auto: create
    generate-ddl: true
    show-sql: true
